server:
  port: 7890
  servlet:
    context-path: /
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: always
    include-exception: true
spring:
  application:
    name: spring-rest-qds-notas
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://sql10.freemysqlhosting.net/sql10526817
    #url: jdbc:mysql://localhost:3306/universidad
    username: sql10526817
    password: t9ymGeziqu
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true
jwt:
  secret: ll@v3